CC = g++
FLAGS = -O3 -fopenmp -std=c++11
EXECS = omp_solved2 omp_solved3 omp_solved4 omp_solved5 omp_solved6 val_test01_solved val_test02_solved MMult1 jacobi2D-omp gs2D-omp

all: ${EXECS}

omp_solved2: omp_solved2.c
	${CC} ${FLAGS} $^ -o omp_solved2

omp_solved3: omp_solved3.c
	${CC} ${FLAGS} $^ -o omp_solved3

omp_solved4: omp_solved4.c
	${CC} ${FLAGS} $^ -o omp_solved4

omp_solved5: omp_solved5.c
	${CC} ${FLAGS} $^ -o omp_solved5

omp_solved6: omp_solved6.c
	${CC} ${FLAGS} $^ -o omp_solved6

val_test01_solved: val_test01_solved.cpp
	${CC} ${FLAGS} $^ -o val_test01_solved

val_test02_solved: val_test02_solved.cpp
	${CC} ${FLAGS} $^ -o val_test02_solved

MMult1: MMult1.cpp
	${CC} ${FLAGS} $^ -o MMult1

jacobi2D-omp: jacobi2D-omp.cpp
	${CC} ${FLAGS} $^ -o jacobi2D-omp -lm

gs2D-omp: gs2D-omp.cpp
	${CC} ${FLAGS} $^ -o gs2D-omp -lm

clean:
	rm -f ${EXECS}